theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
scrolloff = 8
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.insert]
C-c = "normal_mode"
